package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

/**
 * ApplyTableId generated by hbm2java
 */
public class ApplyTableId implements java.io.Serializable {

	private String type;
	private String zjhm;
	private String desp;
	private String userid;
	private String userxm;
	private String orgcode;
	private String orgname;
	private String applytime;
	private Integer status;
	private String dealxm;
	private String dealid;
	private String dealorgcode;
	private String dealorgname;
	private String dealinfo;
	private String lockorderid;
	private String locktime;

	public ApplyTableId() {
	}

	public ApplyTableId(String type, String zjhm, String desp, String userid,
			String userxm, String orgcode, String orgname, String applytime,
			Integer status, String dealxm, String dealid, String dealorgcode,
			String dealorgname, String dealinfo, String lockorderid,
			String locktime) {
		this.type = type;
		this.zjhm = zjhm;
		this.desp = desp;
		this.userid = userid;
		this.userxm = userxm;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.applytime = applytime;
		this.status = status;
		this.dealxm = dealxm;
		this.dealid = dealid;
		this.dealorgcode = dealorgcode;
		this.dealorgname = dealorgname;
		this.dealinfo = dealinfo;
		this.lockorderid = lockorderid;
		this.locktime = locktime;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getZjhm() {
		return this.zjhm;
	}

	public void setZjhm(String zjhm) {
		this.zjhm = zjhm;
	}

	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUserxm() {
		return this.userxm;
	}

	public void setUserxm(String userxm) {
		this.userxm = userxm;
	}

	public String getOrgcode() {
		return this.orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getApplytime() {
		return this.applytime;
	}

	public void setApplytime(String applytime) {
		this.applytime = applytime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getDealxm() {
		return this.dealxm;
	}

	public void setDealxm(String dealxm) {
		this.dealxm = dealxm;
	}

	public String getDealid() {
		return this.dealid;
	}

	public void setDealid(String dealid) {
		this.dealid = dealid;
	}

	public String getDealorgcode() {
		return this.dealorgcode;
	}

	public void setDealorgcode(String dealorgcode) {
		this.dealorgcode = dealorgcode;
	}

	public String getDealorgname() {
		return this.dealorgname;
	}

	public void setDealorgname(String dealorgname) {
		this.dealorgname = dealorgname;
	}

	public String getDealinfo() {
		return this.dealinfo;
	}

	public void setDealinfo(String dealinfo) {
		this.dealinfo = dealinfo;
	}

	public String getLockorderid() {
		return this.lockorderid;
	}

	public void setLockorderid(String lockorderid) {
		this.lockorderid = lockorderid;
	}

	public String getLocktime() {
		return this.locktime;
	}

	public void setLocktime(String locktime) {
		this.locktime = locktime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplyTableId))
			return false;
		ApplyTableId castOther = (ApplyTableId) other;

		return ((this.getType() == castOther.getType()) || (this.getType() != null
				&& castOther.getType() != null && this.getType().equals(
				castOther.getType())))
				&& ((this.getZjhm() == castOther.getZjhm()) || (this.getZjhm() != null
						&& castOther.getZjhm() != null && this.getZjhm()
						.equals(castOther.getZjhm())))
				&& ((this.getDesp() == castOther.getDesp()) || (this.getDesp() != null
						&& castOther.getDesp() != null && this.getDesp()
						.equals(castOther.getDesp())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null && castOther.getUserid() != null && this
						.getUserid().equals(castOther.getUserid())))
				&& ((this.getUserxm() == castOther.getUserxm()) || (this
						.getUserxm() != null && castOther.getUserxm() != null && this
						.getUserxm().equals(castOther.getUserxm())))
				&& ((this.getOrgcode() == castOther.getOrgcode()) || (this
						.getOrgcode() != null && castOther.getOrgcode() != null && this
						.getOrgcode().equals(castOther.getOrgcode())))
				&& ((this.getOrgname() == castOther.getOrgname()) || (this
						.getOrgname() != null && castOther.getOrgname() != null && this
						.getOrgname().equals(castOther.getOrgname())))
				&& ((this.getApplytime() == castOther.getApplytime()) || (this
						.getApplytime() != null
						&& castOther.getApplytime() != null && this
						.getApplytime().equals(castOther.getApplytime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getDealxm() == castOther.getDealxm()) || (this
						.getDealxm() != null && castOther.getDealxm() != null && this
						.getDealxm().equals(castOther.getDealxm())))
				&& ((this.getDealid() == castOther.getDealid()) || (this
						.getDealid() != null && castOther.getDealid() != null && this
						.getDealid().equals(castOther.getDealid())))
				&& ((this.getDealorgcode() == castOther.getDealorgcode()) || (this
						.getDealorgcode() != null
						&& castOther.getDealorgcode() != null && this
						.getDealorgcode().equals(castOther.getDealorgcode())))
				&& ((this.getDealorgname() == castOther.getDealorgname()) || (this
						.getDealorgname() != null
						&& castOther.getDealorgname() != null && this
						.getDealorgname().equals(castOther.getDealorgname())))
				&& ((this.getDealinfo() == castOther.getDealinfo()) || (this
						.getDealinfo() != null
						&& castOther.getDealinfo() != null && this
						.getDealinfo().equals(castOther.getDealinfo())))
				&& ((this.getLockorderid() == castOther.getLockorderid()) || (this
						.getLockorderid() != null
						&& castOther.getLockorderid() != null && this
						.getLockorderid().equals(castOther.getLockorderid())))
				&& ((this.getLocktime() == castOther.getLocktime()) || (this
						.getLocktime() != null
						&& castOther.getLocktime() != null && this
						.getLocktime().equals(castOther.getLocktime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getZjhm() == null ? 0 : this.getZjhm().hashCode());
		result = 37 * result
				+ (getDesp() == null ? 0 : this.getDesp().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getUserxm() == null ? 0 : this.getUserxm().hashCode());
		result = 37 * result
				+ (getOrgcode() == null ? 0 : this.getOrgcode().hashCode());
		result = 37 * result
				+ (getOrgname() == null ? 0 : this.getOrgname().hashCode());
		result = 37 * result
				+ (getApplytime() == null ? 0 : this.getApplytime().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getDealxm() == null ? 0 : this.getDealxm().hashCode());
		result = 37 * result
				+ (getDealid() == null ? 0 : this.getDealid().hashCode());
		result = 37
				* result
				+ (getDealorgcode() == null ? 0 : this.getDealorgcode()
						.hashCode());
		result = 37
				* result
				+ (getDealorgname() == null ? 0 : this.getDealorgname()
						.hashCode());
		result = 37 * result
				+ (getDealinfo() == null ? 0 : this.getDealinfo().hashCode());
		result = 37
				* result
				+ (getLockorderid() == null ? 0 : this.getLockorderid()
						.hashCode());
		result = 37 * result
				+ (getLocktime() == null ? 0 : this.getLocktime().hashCode());
		return result;
	}

}
