package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

/**
 * ControlTreeFiled generated by hbm2java
 */
public class ControlTreeFiled implements java.io.Serializable {

	private int id;
	private ControlTree controlTree;
	private String name;
	private String chname;

	public ControlTreeFiled() {
	}

	public ControlTreeFiled(int id) {
		this.id = id;
	}

	public ControlTreeFiled(int id, ControlTree controlTree, String name,
			String chname) {
		this.id = id;
		this.controlTree = controlTree;
		this.name = name;
		this.chname = chname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ControlTree getControlTree() {
		return this.controlTree;
	}

	public void setControlTree(ControlTree controlTree) {
		this.controlTree = controlTree;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getChname() {
		return this.chname;
	}

	public void setChname(String chname) {
		this.chname = chname;
	}

}
