package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ControlTable generated by hbm2java
 */
public class ControlTable implements java.io.Serializable {

	private String orderid;
	private String type;
	private String grade;
	private Integer controlRate;
	private String userxm;
	private String userid;
	private String startdate;
	private Integer status;
	private String desp;
	private Integer dealcount;
	private Integer catchcount;
	private Integer notifycount;
	private String orgcode;
	private String orgname;
	private Set applyTables = new HashSet(0);
	private Set notifies = new HashSet(0);
	private Set applyTables_1 = new HashSet(0);
	private Set messages = new HashSet(0);
	private Set controlObs = new HashSet(0);

	public ControlTable() {
	}

	public ControlTable(String orderid) {
		this.orderid = orderid;
	}

	public ControlTable(String orderid, String type, String grade,
			Integer controlRate, String userxm, String userid,
			String startdate, Integer status, String desp, Integer dealcount,
			Integer catchcount, Integer notifycount, String orgcode,
			String orgname, Set applyTables, Set notifies, Set applyTables_1,
			Set messages, Set controlObs) {
		this.orderid = orderid;
		this.type = type;
		this.grade = grade;
		this.controlRate = controlRate;
		this.userxm = userxm;
		this.userid = userid;
		this.startdate = startdate;
		this.status = status;
		this.desp = desp;
		this.dealcount = dealcount;
		this.catchcount = catchcount;
		this.notifycount = notifycount;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.applyTables = applyTables;
		this.notifies = notifies;
		this.applyTables_1 = applyTables_1;
		this.messages = messages;
		this.controlObs = controlObs;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Integer getControlRate() {
		return this.controlRate;
	}

	public void setControlRate(Integer controlRate) {
		this.controlRate = controlRate;
	}

	public String getUserxm() {
		return this.userxm;
	}

	public void setUserxm(String userxm) {
		this.userxm = userxm;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}

	public Integer getDealcount() {
		return this.dealcount;
	}

	public void setDealcount(Integer dealcount) {
		this.dealcount = dealcount;
	}

	public Integer getCatchcount() {
		return this.catchcount;
	}

	public void setCatchcount(Integer catchcount) {
		this.catchcount = catchcount;
	}

	public Integer getNotifycount() {
		return this.notifycount;
	}

	public void setNotifycount(Integer notifycount) {
		this.notifycount = notifycount;
	}

	public String getOrgcode() {
		return this.orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Set getApplyTables() {
		return this.applyTables;
	}

	public void setApplyTables(Set applyTables) {
		this.applyTables = applyTables;
	}

	public Set getNotifies() {
		return this.notifies;
	}

	public void setNotifies(Set notifies) {
		this.notifies = notifies;
	}

	public Set getApplyTables_1() {
		return this.applyTables_1;
	}

	public void setApplyTables_1(Set applyTables_1) {
		this.applyTables_1 = applyTables_1;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

	public Set getControlObs() {
		return this.controlObs;
	}

	public void setControlObs(Set controlObs) {
		this.controlObs = controlObs;
	}

}
