package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

/**
 * ControlOb generated by hbm2java
 */
public class ControlOb implements java.io.Serializable {

	private int id;
	private ControlTable controlTable;
	private String personType;
	private Integer islock;
	private String zjhm;
	private String zkzjhm;
	private String zkid;
	private Short iszk;

	public ControlOb() {
	}

	public ControlOb(int id) {
		this.id = id;
	}

	public ControlOb(int id, ControlTable controlTable, String personType,
			Integer islock, String zjhm, String zkzjhm, String zkid, Short iszk) {
		this.id = id;
		this.controlTable = controlTable;
		this.personType = personType;
		this.islock = islock;
		this.zjhm = zjhm;
		this.zkzjhm = zkzjhm;
		this.zkid = zkid;
		this.iszk = iszk;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ControlTable getControlTable() {
		return this.controlTable;
	}

	public void setControlTable(ControlTable controlTable) {
		this.controlTable = controlTable;
	}

	public String getPersonType() {
		return this.personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public Integer getIslock() {
		return this.islock;
	}

	public void setIslock(Integer islock) {
		this.islock = islock;
	}

	public String getZjhm() {
		return this.zjhm;
	}

	public void setZjhm(String zjhm) {
		this.zjhm = zjhm;
	}

	public String getZkzjhm() {
		return this.zkzjhm;
	}

	public void setZkzjhm(String zkzjhm) {
		this.zkzjhm = zkzjhm;
	}

	public String getZkid() {
		return this.zkid;
	}

	public void setZkid(String zkid) {
		this.zkid = zkid;
	}

	public Short getIszk() {
		return this.iszk;
	}

	public void setIszk(Short iszk) {
		this.iszk = iszk;
	}

}
