package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private int id;
	private ControlTable controlTable;
	private String userid;
	private String content;
	private String addtime;
	private String phone;
	private String userxm;

	public Message() {
	}

	public Message(int id) {
		this.id = id;
	}

	public Message(int id, ControlTable controlTable, String userid,
			String content, String addtime, String phone, String userxm) {
		this.id = id;
		this.controlTable = controlTable;
		this.userid = userid;
		this.content = content;
		this.addtime = addtime;
		this.phone = phone;
		this.userxm = userxm;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ControlTable getControlTable() {
		return this.controlTable;
	}

	public void setControlTable(ControlTable controlTable) {
		this.controlTable = controlTable;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAddtime() {
		return this.addtime;
	}

	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUserxm() {
		return this.userxm;
	}

	public void setUserxm(String userxm) {
		this.userxm = userxm;
	}

}
