package founder.model2;

// Generated 2018-4-27 18:39:40 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Integer age;
	private String niceName;
	private String name;

	public User() {
	}

	public User(Integer age, String niceName, String name) {
		this.age = age;
		this.niceName = niceName;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getNiceName() {
		return this.niceName;
	}

	public void setNiceName(String niceName) {
		this.niceName = niceName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
