package com.founderinternational.rscenter.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.founderinternational.rscenter.entity.EZDataTree;
import com.founderinternational.rscenter.mapper.EZDataTreeMapper;
import com.founderinternational.rscenter.mapper.EZFunctionMapper;
import com.founderinternational.rscenter.service.EZDataTreeService;

@Repository(value = "eZDataTreeService")
@Transactional
public class EZDataTreeServiceImpl implements EZDataTreeService {

	@Resource(name = "eZDataTreeMapper")
	private EZDataTreeMapper eZDataTreeMapper;
	@Override
	public List<EZDataTree> find(String user) {
		String sql="";
		sql+="SELECT ROWNUM LAYERID, T.* ";
		sql+="  FROM (SELECT T1.SCHEMEID, ";
		sql+="     T1.STDID, ";
		sql+="            T1.STDCODE,";
		sql+="            T1.NODE, ";
		sql+="          NVL(T1.PARENT, T1.THEMEID) PARENT, ";
		sql+="         T1.THEMEID, ";
		sql+="        T1.THEMECODE, ";
		sql+="        T1.OWNER, ";
		sql+="       T1.TABLENAME, ";
		sql+="  T1.ALIASNAME, ";
		sql+="    T1.COMPOSITEPK, ";
		sql+="    T1.MORDER, ";
		sql+="   T1.QUERYFIELDNAME, ";
		sql+="   T1.SPATIALLAYERID, ";
		sql+="   T1.SPATIALLAYERCODE, ";
		sql+="   T1.STYLE, ";
		sql+="   T1.MAPSERVICEIP, ";
		sql+="   T1.FILTER, ";
		sql+="   T1.LLEVEL, ";
		sql+="   T1.SOURCEURI, ";
		sql+="   T1.DEFAULTFILTER, ";
		sql+="  (SELECT distinct (ORDER_FILTER) ";
		sql+="    FROM (SELECT LAYERID, ";
		sql+="     LTRIM(MAX(ORDER_FILTER), ',') ORDER_FILTER, ";
		sql+="    (SELECT CODE ";
		sql+="   FROM EZSPATIAL.EZ_STD_LAYERS_LAYER ";
		sql+="   WHERE ID = LAYERID) CODE ";
		sql+="  FROM (SELECT T.*, ";
		sql+="       SYS_CONNECT_BY_PATH(EXPR || FIELDPX || ";
		sql+="                      NULLPX, ";
		sql+="                        ',') ORDER_FILTER ";
		sql+="    FROM (SELECT T.*, ";
		sql+="     LAYERID || ROW_NUMBER() OVER(PARTITION BY LAYERID ORDER BY SEQ) RN, ";
		sql+="     DECODE(ROW_NUMBER() ";
		sql+="            OVER(PARTITION BY LAYERID ";
		sql+="                 ORDER BY SEQ) - 1, ";
		sql+="            0, ";
		sql+="           NULL, ";
		sql+="            LAYERID || ROW_NUMBER() ";
		sql+="          OVER(PARTITION BY LAYERID ";
		sql+="         ORDER BY SEQ) - 1) RN1 ";
		sql+="  FROM (SELECT LAYERID, ";
		sql+="    EXPR, ";
		sql+="    DECODE(FLD_ASC, ";
		sql+="   0, ";
		sql+="  ' DESC', ";
		sql+="  ' ASC') FIELDPX, ";
		sql+="  DECODE(FLD_NULLFIRST, ";
		sql+="  	0, ";
		sql+="  ' NULLS LAST', ";
		sql+="  ' NULLS FIRST') NULLPX, ";
		sql+="  SEQ ";
		sql+="  FROM EZSPATIAL.EZ_STD_LAYERS_ORDER T ";
		sql+="   ORDER BY LAYERID, SEQ) T) T ";
		sql+="  CONNECT BY RN1 = PRIOR RN ";
		sql+="  START WITH RN1 IS NULL) ";
		sql+="  GROUP BY LAYERID) ";
		sql+="  WHERE CODE = T1.SPATIALLAYERCODE) ORDER_FILTER ";
		sql+="  FROM (SELECT * FROM V_GA_DATA_BASIC) T1, ";
		sql+="  	(SELECT LAYERCODE ";
		sql+="  	FROM (select distinct ts.tablecode layercode ";
		sql+="  	from (select distinct orgRole.Themecode, ";
		sql+="  	orgRole.Tablecode ";
		sql+="  from EZ_P_ORG_ROLE orgRole, ";
		sql+="  EZ_R_ORG_USER orgUser ";
		sql+="  where orgUser.Orgcode = orgRole.Orgcode ";
		sql+="  and orgUser.Userid = '"+user+"' ";
		sql+="  and orgRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct userRole.Themecode, ";
		sql+="  userRole.Tablecode ";
		sql+="  from EZ_P_USER_ROLE userRole ";
		sql+="  where userRole.Userid = '"+user+"' ";
		sql+="  and userRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct posrole1.Themecode, ";
		sql+="  posrole1.tablecode ";
		sql+="  from EZ_P_POSITION_ROLE1 posrole1, ";
		sql+="  EZ_R_POSITION_USER  posUser ";
		sql+="  where posrole1.ropid = posUser.Posid ";
		sql+="  and posUser.Userid = '"+user+"' ";
		sql+="  and posrole1.Themecode is not null) ts)) T2 ";
		sql+="  WHERE T1.SPATIALLAYERCODE = T2.LAYERCODE ";
		sql+="  AND THEMECODE IN ";
		sql+="  (SELECT THEMECODE ";
		sql+="  FROM (select distinct ts.themecode ";
		sql+="  from (select distinct orgRole.Themecode, ";
		sql+="  orgRole.Tablecode ";
		sql+="  from EZ_P_ORG_ROLE orgRole, ";
		sql+="  EZ_R_ORG_USER orgUser ";
		sql+="  where orgUser.Orgcode = orgRole.Orgcode ";
		sql+="  and orgUser.Userid = '"+user+"' ";
		sql+="  and orgRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct userRole.Themecode, ";
		sql+="  userRole.Tablecode ";
		sql+="  from EZ_P_USER_ROLE userRole ";
		sql+="  where userRole.Userid = '"+user+"' ";
		sql+="  and userRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct posrole1.Themecode, ";
		sql+="  posrole1.tablecode ";
		sql+="  from EZ_P_POSITION_ROLE1 posrole1, ";
		sql+="  	EZ_R_POSITION_USER  posUser ";
		sql+="  where posrole1.ropid = posUser.Posid ";
		sql+="  and posUser.Userid = '"+user+"' ";
		sql+="  and posrole1.Themecode is not null) ts)) ";
		sql+="  UNION ";
		sql+="  SELECT T1.SCHEMEID, ";
		sql+="  T1.STDID, ";
		sql+="  T1.STDCODE, ";
		sql+="  T1.NODE, ";
		sql+="  NVL(T1.PARENT, T1.THEMEID) PARENT, ";
		sql+="  T1.THEMEID, ";
		sql+="  T1.THEMECODE, ";
		sql+="  T1.OWNER, ";
		sql+="  T1.TABLENAME, ";
		sql+="  T1.ALIASNAME, ";
		sql+="  T1.COMPOSITEPK, ";
		sql+="  T1.MORDER, ";
		sql+="  T1.QUERYFIELDNAME, ";
		sql+="  T1.SPATIALLAYERID, ";
		sql+="  T1.SPATIALLAYERCODE, ";
		sql+="  T1.STYLE, ";
		sql+="  T1.MAPSERVICEIP, ";
		sql+="  T1.FILTER, ";
		sql+="  T1.LLEVEL, ";
		sql+="  T1.SOURCEURI, ";
		sql+="  T1.DEFAULTFILTER, ";
		sql+="  '' ORDER_FILTER ";
		sql+="  FROM (SELECT * FROM V_GA_DATA_BASIC) T1, ";
		sql+="  (SELECT THEMECODE ";
		sql+="  FROM (select distinct ts.themecode ";
		sql+="  from (select distinct orgRole.Themecode, ";
		sql+="  orgRole.Tablecode ";
		sql+="  from EZ_P_ORG_ROLE orgRole, ";
		sql+="  EZ_R_ORG_USER orgUser ";
		sql+="  where orgUser.Orgcode = orgRole.Orgcode ";
		sql+="  and orgUser.Userid = '"+user+"' ";
		sql+="  and orgRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct userRole.Themecode, ";
		sql+="  userRole.Tablecode ";
		sql+="  from EZ_P_USER_ROLE userRole ";
		sql+="  where userRole.Userid = '"+user+"' ";
		sql+="  and userRole.Themecode is not null ";  
		sql+="  	union all ";
		sql+="  	select distinct posrole1.Themecode, ";
		sql+="  	posrole1.tablecode ";
		sql+="  	from EZ_P_POSITION_ROLE1 posrole1, ";
		sql+="  	EZ_R_POSITION_USER  posUser ";
		sql+="  	where posrole1.ropid = posUser.Posid ";
		sql+="  and posUser.Userid = '"+user+"' ";
		sql+=" and posrole1.Themecode is not null) ts)) T2 ";
		sql+="  	WHERE T1.THEMECODE = T2.THEMECODE ";
		sql+="  	AND (UPPER(TABLENAME) = UPPER('UNKNOWN') OR TABLENAME IS NULL) ";
		sql+="  UNION ";
		sql+="  SELECT distinct (SELECT SCHEMEID ";
		sql+="  FROM EZSPATIAL.EZ_STD_DEF ";
		sql+="    WHERE ID = T.STDID) SCHEMEID, ";
		sql+="  T.STDID, ";
		sql+="  NULL STDCODE, ";
		sql+="  TO_CHAR(ID) NODE, ";
		sql+="  NULL PARENT, ";  
		sql+="  ID THEMEID, ";
		sql+="  CODE THEMECODE, ";
		sql+="  DBUSER OWNER, ";
		sql+="  NULL TABLENAME, ";
		sql+="  NAME ALIASNAME, ";
		sql+="  NULL COMPOSITEPK, ";
		sql+="  ID || '000' || ID MORDER, ";
		sql+="  NULL QUERYFIELDNAME, ";
		sql+="  NULL SPATIALLAYERID, ";
		sql+="  NULL SPATIALLAYERCODE, ";
		sql+="  	NULL STYLE, ";
		sql+="  	'' MAPSERVICEIP, ";
		sql+="  NULL FILTER, ";
		sql+="  0 LLEVEL, ";
		sql+="  '' SOURCEURI, ";
		sql+="  '' DEFAULTFILTER, ";
		sql+="  '' ORDER_FILTER ";
		sql+="  FROM (SELECT T1.*, T2.CODE STDCODE ";
		sql+="  FROM EZSPATIAL.EZ_STD_LAYERS_THEME T1, ";
		sql+="  EZSPATIAL.EZ_STD_DEF          T2 ";
		sql+="  WHERE T1.CODE IN ";
		sql+="  (SELECT THEMECODE ";
		sql+="  FROM (select distinct ts.themecode ";
		sql+="  from (select distinct orgRole.Themecode, ";
		sql+="  orgRole.Tablecode ";
		sql+="  from EZ_P_ORG_ROLE orgRole, ";
		sql+="  EZ_R_ORG_USER orgUser ";
		sql+="  where orgUser.Orgcode = orgRole.Orgcode ";
		sql+="  and orgUser.Userid = '"+user+"' ";
		sql+="  and orgRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct userRole.Themecode, ";
		sql+="  userRole.Tablecode ";
		sql+="  from EZ_P_USER_ROLE userRole ";
		sql+="  where userRole.Userid = '"+user+"' ";
		sql+="  and userRole.Themecode is not null ";
		sql+="  union all ";
		sql+="  select distinct posrole1.Themecode, ";
		sql+="  posrole1.tablecode ";
		sql+="  from EZ_P_POSITION_ROLE1 posrole1, ";
		sql+="  EZ_R_POSITION_USER  posUser ";
		sql+="  where posrole1.ropid = posUser.Posid ";
		sql+="  and posUser.Userid = '"+user+"' ";
		sql+="  and posrole1.Themecode is not null) ts) ";
		sql+="  GROUP BY THEMECODE)) T) T ";
		sql+="  ORDER BY MORDER ";
        //System.out.println(sql);
		return this.eZDataTreeMapper.operateReturnBeans(sql);
	}

}
